name: Expo Storybook Preview

defaults:
  run:
    working-directory: apps/storybook-react-native

on:
  pull_request:
    paths:
      - "package.json"
      - "apps/expo/package.json"
      - "apps/expo/app.config.js"
      - "apps/expo/.env.*"
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - ".github/workflows/**"
      - "**.patch"
      - "**.lock"

concurrency:
  group: storybook-preview-${{ github.event_name }}-${{ github.ref }}-storybook
  cancel-in-progress: true

jobs:
  pr-preview:
    name: PR Preview
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # ðŸ‘ˆ Required to retrieve git history

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: 8BitJonny/gh-get-current-pr@1.3.0
        id: PR
        name: Check if we're in a PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set up Expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          eas-cache: true
          expo-cache: true
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: EAS Update
        if: success() && steps.PR.outputs.number != ''
        run: NODE_OPTIONS=--max-old-space-size=5120 EXPO_DEBUG=true STAGE=development eas update --branch pr-${{ steps.PR.outputs.number }} --message "Deploy to PR preview"

      - name: Preview Deep Link
        id: publish-url
        run: echo "::set-output name=url::exp+io.showtime.storybook://expo-development-client/?url=https://u.expo.dev/e77d5b68-bb27-45da-aa5c-96c1fdbf6706&channel-name=pr-${{ steps.PR.outputs.number }}"

      - name: Find PR Comment
        uses: peter-evans/find-comment@v1
        if: success() && steps.PR.outputs.number != ''
        id: existing-comment
        with:
          issue-number: ${{ steps.PR.outputs.number }}
          body-includes: PR Preview - Storybook

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        if: success() && steps.PR.outputs.number != ''
        with:
          comment-id: ${{ steps.existing-comment.outputs.comment-id }}
          issue-number: ${{ steps.PR.outputs.number }}
          edit-mode: replace
          body: |
            ## PR Preview - Storybook

            This pull request preview deployment is now available.

            âœ… Preview: <a href="${{ steps.publish-url.outputs.url }}">${{ steps.publish-url.outputs.url }}</a>

            <a href="${{ steps.publish-url.outputs.url }}"><img src="https://api.qrserver.com/v1/create-qr-code/?size=512x512&data=${{ steps.publish-url.outputs.url }}" height="512px" width="512px" /></a>

            Comment ID: ${{ steps.existing-comment.outputs.comment-id }}
