name: Mobile Dev Action iOS

defaults:
  run:
    working-directory: apps/expo
on:
  pull_request:
    branches: ["staging"]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable

      - name: Expo prebuild
        run: yarn E2E:build

      - name: Build with Xcode
        run: |
          DERIVED_DATA_PATH=/tmp/Showtime-$(uuidgen) 

          cd ios/ && E2E=true FLIPPER_DISABLE=1 STAGE=development xcodebuild -workspace Showtime.xcworkspace    \
                    -scheme Showtime                              \
                    -configuration Release                        \
                    -sdk iphonesimulator                          \
                    -derivedDataPath "$DERIVED_DATA_PATH"         \
                    clean build

          echo "APP_DIR_PATH=${DERIVED_DATA_PATH}/Build/Products/Release-iphonesimulator/Showtime.app" >>$GITHUB_ENV

      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ${{ env.APP_DIR_PATH }}
          env: |
            PLATFORM=ios
